#!/usr/bin/env sh
# . "${0%/*}/h"

# Define your include and exclude patterns
INCLUDE="**/*.{test,spec}.?(c|m)[jt]s?(x)"
EXCLUDE="**/node_modules/** **/dist/** **/cypress/** **/.{idea,git,cache,output,temp}/** **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*"

# Find test files respecting the include and exclude patterns
# Use 'find' or 'dir /s /b' based on the OS
if [ "$(uname -s)" = "Darwin" ] || [ "$(uname -s)" = "Linux" ]; then
    TEST_FILES=$(find . -type f \( -path "$INCLUDE" \) ! -path "$EXCLUDE" 2>/dev/null)
else
    TEST_FILES=$(dir /s /b $INCLUDE | findstr /v /i $EXCLUDE)
fi

if [ -n "$TEST_FILES" ]; then
    echo "Running pnpm test..."
    pnpm test
    TEST_EXIT_CODE=$?
else
    echo "No test files found, skipping pnpm test."
    TEST_EXIT_CODE=0
fi

echo "Running pnpm build..."
pnpm build
BUILD_EXIT_CODE=$?

# Check if both commands were successful
if [ $TEST_EXIT_CODE -eq 0 ] && [ $BUILD_EXIT_CODE -eq 0 ]; then
    echo "All checks passed. Proceeding with commit."
    exit 0
else
    echo "Pre-commit checks failed."
    [ $TEST_EXIT_CODE -ne 0 ] && echo "pnpm test failed."
    [ $BUILD_EXIT_CODE -ne 0 ] && echo "pnpm build failed."
    exit 1
fi